### ISSUE TITLE
separate repository for the ICS data

### ISSUE THREAD

**Issue by klaernie** [paulbrejla/ferien-api#11]
This is mainly a suggestion to make maintaining the data in the long run easier.

Would it be a good idea to put the currently used data into a separate repo, that than is checked out automatically by the Dockerfile, and have a github workflow triggering rebuilds of the docker container, so the docker container is a combination of the latest data and code?

This then would make it possible to point everybody willing to help fix data issues to that repo, and just a click of the merge button on your end.

While I'm useless with java code and packaging I'm fairly confident that I could prep a repo and PR implementing the workflow. But I would rather not make this investment if you think this building effort is not worth it in the long run.

**Comment by paulbrejla** [comment]
Hey, good idea!

Can you take care of opening that repo (and possibly syncing with others to provide the ics files)? Happy to incorporate this.

**Comment by klaernie** [comment]
Sure - will happily do that. But I guess it would be best to place that in the same namespace as ferien-api itself. I'll setup a ferien-api-data repo that you can later move into place.
But one thing for this would be a tarball of the existing files. Could you throw a tarball of the existing dataset into here?

**Comment by paulbrejla** [comment]
I am not sure if I can find all the old ICS files I've used. Should not be a major issue though as these follow a fairly simple pattern (see the example file under test/resources).

How do you think we should pull the ics files into the app? I see two ways:

1. Pull the files from the new repo during the build process
2. Pull the files from the new repo periodically during runtime (could avoid requiring new builds when ics files are added) 

Cheers
Paul

**Comment by paulbrejla** [comment]
Check this https://github.com/paulbrejla/ferien-api/pull/16.

**Comment by klaernie** [comment]
> I am not sure if I can find all the old ICS files I've used. Should not be a major issue though as these follow a fairly simple pattern (see the example file under test/resources).

I just wanted to start with the ones that are currently in-use, to avoid making a mistake.

> How do you think we should pull the ics files into the app?

Both ways you mentioned are very valid in their own way.

I'd say one should build a software-only docker container here that can be used to host the software excluding the data.
Then in the -data repo one can build a docker container that mixes this software-only container with the data in the repo to produce a static container that can be used indefinitely offline.

Pulling data at runtime has it's charme, since it means one can start a container and forget about it until something breaks. But this comes at the cost of repeatedly hitting the "source" of the data asking for updates, even if there are none for weeks on end.

Using git as a transport is fairly efficient, but one might argue that using plain HTTP connecting to ferien-api.de could also be a viable option.

I'd think for your "personal" use case loading from a git repo would be the best path, but I personally wouldn't recommend that way to users.
There are also other ways of triggering updates in infrastructure. I like using a github action to deploy directly into production - since my personal favourite is hosting stuff in Kubernetes clusters this is [Azure/k8s-deploy](https://github.com/Azure/k8s-deploy) like [in this example](https://github.com/hssb-racers/LockoutBoard/blob/main/.github/workflows/build-image.yaml#L57-L81).

So, in the end I'd prefer to host ferien-api locally in my Kubernetes cluster at home, and configure my homeassistant instance to connect to it there. I'd point my Kubernetes cluster to always pull the latest data-containing image, which means it will check each time the container gets restarted. That would result in an update frequency of once a month, which would fulfill my needs.

**Comment by paulbrejla** [comment]
Thank you for your feedback - I have now started to implement a loader that fetches the ics files from a configurable git repo. 

This will add more flexibility by not relying on the files being on the classpath during compile time. Other approaches through infrastructure are still possible.
