### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by Nosleep28** [paulbrejla/ferien-api#12]
I have an ics with all german holliday ready, but how can I provide it to be used by the api?

**Comment by Nosleep28** [comment]
Does anyone have a working stack, which I can co-use ? I'm not into  Spring Boot and Kotlin and don't know where to start to host my own. I found a hoster, but I think you still have to know what you are doing.

**Comment by paulbrejla** [comment]
Hey, I am currently working on fixing the open issues - I've also attached an example ics you can use to populate the db. Hope this helps!

**Comment by paulbrejla** [comment]
Servus, if you encounter any data issues and would like to help make the API more reliable, please refer to https://github.com/paulbrejla/ferien-api#some-dates-are-wrong---can-you-fix-them.
