### ISSUE TITLE
Data discrepency

### ISSUE THREAD

**Issue by Zawar92** [paulbrejla/ferien-api#20]
While using [Api](https://ferien-api.de/api/v1/holidays) it seems that school holidays in Hessen (HE) last over two years and in Rheinland-Pfalz (RP) as well, seems like the end date is wrong for these entries, but the year information is correct.
e.g. see entries 1 and 7

Can you give me an update on it? It would be really helpful.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/26454033/222711634-871374d3-4336-41c0-a5fc-0b6658d9e01c.png">

**Comment by darian-heede** [comment]
@paulbrejla thank you for this great API!

This issue relates to the PRs [here](https://github.com/paulbrejla/ferien-api-data/pull/6) and [here](https://github.com/paulbrejla/ferien-api-data/pull/8). Any plans to merge them soon?

**Comment by paulbrejla** [comment]
Merged them @darian-heede

**Comment by darian-heede** [comment]
Thank you @paulbrejla! Any plans on reviewing and merging the other open PRs? We still have a few errors in the data as is.

**Comment by paulbrejla** [comment]
Merged all of the existing PRs.
