### ISSUE TITLE
ferien-api.de offline 

### ISSUE THREAD

**Issue by RFM69CW** [paulbrejla/ferien-api#23]
Since yesterday the website is not reachable and also the api does not work anymore.

**Comment by RFM69CW** [comment]
Great thank you. Your api is great. Thank you for your effort and work🙂

**Comment by RFM69CW** [comment]
Hi unfortunately the api is offline again since a few days ☹️

**Comment by paulbrejla** [comment]
It will remain down until I have put basic DDOS mitigation in place as it is getting hammered as soon as it comes up.
