### ISSUE TITLE
Import von Feiertagen

### ISSUE THREAD

**Issue by berti34** [paulbrejla/ferien-api#4]
Hallo! 

Hier gibt es eine Quelle von allgemeingültigen Feiertagen aller relevanten Religionen usw. im ICS-Format:
https://www.mkffi.nrw/pressemitteilung/interreligioeser-kalender-2021-gibt-ueberblick-ueber-feiertage-von-13

https://www.mkffi.nrw/sites/default/files/asset/document/ik2021.ics

Wie wäre es mit dem Import?

**Comment by datenleck** [comment]
Die haben wohlmöglich auf Englisch umgestellt:
https://www.mkffi.nrw/sites/default/files/documents/ik2021.ics

**Comment by paulbrejla** [comment]
Hi,

die Integration ist möglich, dann aber vermutlich unter einem anderen Endpunkt. Nötige Anpassungen:

1. API-Struktur um nicht nach Bundesland aufgeschlüsselte Feiertage auszugeben.
2. Importprozess muss entsprechend ICS-Files laden können (Struktur des Dateinamens, Struktur des ICS).

Beizeiten kann ich dazu einen Änderung bereitstellen.
