### ISSUE TITLE
Vacations in Hessen 2021 are duplicated?

### ISSUE THREAD

**Issue by asmaier** [paulbrejla/ferien-api#7]
When doing the following request (from the Swagger API)

`curl -X GET "https://ferien-api.de/api/v1/holidays/HE/2021" -H "accept: application/json"`

I do get as result:

`[   {     "start": "2021-04-06T00:00Z",     "end": "2021-04-17T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "osterferien",     "slug": "osterferien-2021-HE"   },   {     "start": "2021-07-19T00:00Z",     "end": "2021-08-28T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "sommerferien",     "slug": "sommerferien-2021-HE"   },   {     "start": "2021-10-11T00:00Z",     "end": "2021-10-24T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "herbstferien",     "slug": "herbstferien-2021-HE"   },   {     "start": "2021-12-23T00:00Z",     "end": "2022-01-09T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "weihnachtsferien",     "slug": "weihnachtsferien-2021-HE"   },   {     "start": "2021-04-06T00:00Z",     "end": "2021-04-17T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "osterferien hessen 2021",     "slug": "osterferien hessen 2021-2021-HE"   },   {     "start": "2021-07-19T00:00Z",     "end": "2021-08-28T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "sommerferien hessen 2021",     "slug": "sommerferien hessen 2021-2021-HE"   },   {     "start": "2021-10-11T00:00Z",     "end": "2021-10-24T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "herbstferien hessen 2021",     "slug": "herbstferien hessen 2021-2021-HE"   },   {     "start": "2021-12-23T00:00Z",     "end": "2022-01-09T00:00Z",     "year": 2021,     "stateCode": "HE",     "name": "weihnachtsferien hessen 2021/2022",     "slug": "weihnachtsferien hessen 2021/2022-2021-HE"   } ]`

It seems there are duplicate entries: `osterferien` and `osterferien hessen 2021`, `sommerferien` and `sommerferien hessen 2021`, etc .

**Comment by asmaier** [comment]
In addition I found that for Saarland in 2018

`curl -X GET "https://ferien-api.de/api/v1/holidays/SL/2018" -H "accept: application/json"`

the response is missing the `herbstferien` and the `weihnachtsferien`.

**Comment by asmaier** [comment]
Actually there are even more data problems. Many vacation have a wrong duration of only one day

```
BW 2021 osterferien
BW 2021 herbstferien
BW 2022 osterferien
BW 2022 herbstferien
BE 2019 herbstferien
MV 2019 herbstferien
MV 2021 pfingstferien
```

It seems the data and/or the data parsing for ferien-api is not very reliable.

**Comment by paulbrejla** [comment]
Servus, if you encounter any data issues and would like to help make the API more reliable, please refer to https://github.com/paulbrejla/ferien-api#some-dates-are-wrong---can-you-fix-them.
