### ISSUE TITLE
Wrong precision for date calculation

### ISSUE THREAD

**Issue by fmuecke** [paulbrejla/ferien-api#9]

**Comment by fmuecke** [comment]
Das Ferienende ist aktuell 0:00 Uhr in der Früh. Sollte es stattdessen nicht 23:59 Uhr sein?
Oder bei der Ausgabe das Format verkürzen, so dass die Uhrzeit wegfällt?

**Comment by stangls** [comment]
Das Zeit-Intervall ist am Ende offen.
Das sollte so dokumentiert werden.

Eine Angabe wie 23:59 wäre ebenfalls falsch.
Sind denn in der letzten Minute an diesem Tag keine Ferien mehr? ;-)

**Comment by paulbrejla** [comment]
Hi, gerne fixen und einen PR erstellen :-). Zeitlich bedingt komme ich momentan leider nicht dazu.
